language: ruby

rvm:
  - 2.2.2
  - 2.1.6
  - 2.0.0
  - 1.9.3
  - jruby-19mode

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always

before_install: "gem install bundler -v 1.10.5"
install: "bundle --jobs 4"
script: "bundle exec rspec"
